POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "penny boxman",
  "number": "555-555-5555"
}

###
POST https://boiling-fortress-91832.herokuapp.com/api/persons
content-type: application/json

{
  "name": "penny boxman",
  "number": "555-555-5555"
}